development:
  adapter: postgresql
  encoding: unicode
  database: wdi-rockr_development
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  #host: localhost
  #port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: wdi-rockr_test
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  #host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: wdi-rockr_production
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  #host: localhost